### ISSUE TITLE
There is already an account with the login name

### ISSUE THREAD

**Issue by kaihendry** [unee-t/frontend#898]
I signed up a new account https://case.dev.unee-t.com/signup using my existing email address.

Instead of getting an UI error that I've signed up before I get no feedback. So I don't know what to do. It should perhaps just go the Forgotten password route.

Looking at the meteor logs I see:

```
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at Request._callback (packages/http.js:140:24)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at Request.self.callback (/home/node/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at emitTwo (events.js:126:13)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at Request.emit (events.js:214:7)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at Request.<anonymous> (/home/node/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at emitOne (events.js:116:13)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at Request.emit (events.js:211:7)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at IncomingMessage.<anonymous> (/home/node/app/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at Object.onceWrapper (events.js:313:30)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at emitNone (events.js:111:20)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at IncomingMessage.emit (events.js:208:7)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at endReadableNT (_stream_readable.js:1064:12)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at _combinedTickCallback (internal/process/next_tick.js:139:11)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)     at process._tickDomainCallback (internal/process/next_tick.js:219:9)
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)   response:
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)    { statusCode: 400,
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)      content: '{"documentation":"https://bugzilla.readthedocs.org/en/5.0/api/","code":500,"error":true,"message":"There is already an account with the login name kai.hendry@gmail.com."}',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)      headers:
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)       { date: 'Mon, 10 Feb 2020 01:03:48 GMT',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         'content-type': 'application/json; charset=UTF-8',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         'transfer-encoding': 'chunked',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         connection: 'close',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         'set-cookie': [Array],
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         server: 'Apache/2.4.29 (Ubuntu)',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         'access-control-allow-headers': 'origin, content-type, accept, x-requested-with',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         'access-control-allow-origin': '*',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         'x-content-type-options': 'nosniff',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         'x-frame-options': 'SAMEORIGIN',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         'x-xss-protection': '1; mode=block',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         etag: 'ngIxvF6+wE2cfeK99L7tbA' },
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)      data:
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)       { documentation: 'https://bugzilla.readthedocs.org/en/5.0/api/',
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         code: 500,
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         error: true,
[2020-02-10T09:03:48+08:00] (ecs/meteor/2590a2d4-2e1d-4cb6-ba26-4b8580ecd882)         message: 'There is already an account with the login name kai.hendry@gmail.com.' } } }

```

**Comment by kaihendry** [comment]
Might be related to apienroll failing here: https://github.com/unee-t/apienroll/issues/8
